data_path: "L:/Project-Gurobi/Workspace3/E4ST/Data/mpc_210711_allTech"
out_path: "../out/highs"
years:
  - "y2030"
mods: []
save_model_presolve: false
gen_file: "L:/Project-Gurobi/Workspace3/E4ST/Data/mpc_210711_allTech/gen.csv"
demand_file: "L:/Project-Gurobi/Workspace3/E4ST/Data/mpc_210711_allTech/demand.csv"
demand_match_file: "L:/Project-Gurobi/Workspace3/E4ST/Data/mpc_210711_allTech/demand_match.csv"
bus_file: "L:/Project-Gurobi/Workspace3/E4ST/Data/mpc_210711_allTech/bus.csv"
branch_file: "L:/Project-Gurobi/Workspace3/E4ST/Data/mpc_210711_allTech/branch.csv"
hours_file: "L:/Project-Gurobi/Workspace3/E4ST/Data/mpc_210711_allTech/hours.csv"
optimizer:
  type: "HiGHS"
  log_file: "HiGHS.log"
  solver: "ipm"
  run_crossover: "off"
  parallel: "off"
config_file: "L:/Project-Gurobi/Workspace3/E4ST/Data/mpc_210711_allTech\\config_gurobi.yml"
