# From https://github.com/JuliaPlots/Plots.jl/blob/master/.github/workflows/benchmark.yml
name: benchmarks

on:
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Benchmark:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: "1.10"
      - uses: julia-actions/julia-buildpkg@latest
      - name: Install dependencies
        run: |
          julia -e 'using Pkg; Pkg.add([Pkg.PackageSpec(name="PkgBenchmark"), Pkg.PackageSpec(name="BenchmarkCI", version="0.1"), Pkg.PackageSpec(name="JSON", version="0.21.3")])'
      - name: Run benchmarks
        run: julia -e 'using BenchmarkCI; BenchmarkCI.judge(baseline="origin/main")'
      - name: Post results
        run: julia -e 'using BenchmarkCI; BenchmarkCI.postjudge()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show Julia environment info
        run: |
          julia -e 'println("Julia version: ", VERSION); using Pkg; Pkg.status()'
